import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    name: 'CnasTesting',
    path: '/cnas/testing',
    redirect: '/cnas/testing/tasks',
    meta: { icon: 'lucide:flask-conical', order: 20, title: '检测管理' },
    children: [
      { name: 'TM01', path: '/cnas/testing/tasks', component: () => import('#/views/cnas/testing/TM01.vue'), meta: { icon: 'lucide:list-checks', title: '检测任务列表' } },
      { name: 'TM03', path: '/cnas/testing/task-detail', component: () => import('#/views/cnas/testing/TM03.vue'), meta: { icon: 'lucide:clipboard-list', title: '检测任务详情' } },
      { name: 'TM02', path: '/cnas/testing/schedule', component: () => import('#/views/cnas/testing/TM02.vue'), meta: { hideInMenu: true, title: '任务排程' } },
      { name: 'TM04', path: '/cnas/testing/start', component: () => import('#/views/cnas/testing/TM04.vue'), meta: { hideInMenu: true, title: '任务领用与开工' } },
      { name: 'TM05', path: '/cnas/testing/records', component: () => import('#/views/cnas/testing/TM05.vue'), meta: { hideInMenu: true, title: '原始记录编辑器' } },
      { name: 'TM06', path: '/cnas/testing/instrument-data', component: () => import('#/views/cnas/testing/TM06.vue'), meta: { hideInMenu: true, title: '仪器数据导入' } },
      { name: 'TM07', path: '/cnas/testing/calculation', component: () => import('#/views/cnas/testing/TM07.vue'), meta: { hideInMenu: true, title: '数据计算与结果生成' } },
      { name: 'TM08', path: '/cnas/testing/resource-check', component: () => import('#/views/cnas/testing/TM08.vue'), meta: { hideInMenu: true, title: '检测资源核验' } },
      { name: 'TM09', path: '/cnas/testing/exception', component: () => import('#/views/cnas/testing/TM09.vue'), meta: { hideInMenu: true, title: '检测异常与暂停' } },
      { name: 'TM10', path: '/cnas/testing/retest', component: () => import('#/views/cnas/testing/TM10.vue'), meta: { hideInMenu: true, title: '复检与重测申请' } },
      { name: 'TM11', path: '/cnas/testing/result-summary', component: () => import('#/views/cnas/testing/TM11.vue'), meta: { hideInMenu: true, title: '检测结果汇总' } },
      { name: 'TM12', path: '/cnas/testing/result-review', component: () => import('#/views/cnas/testing/TM12.vue'), meta: { hideInMenu: true, title: '结果复核工作台' } },
      { name: 'TM13', path: '/cnas/testing/quality-control', component: () => import('#/views/cnas/testing/TM13.vue'), meta: { hideInMenu: true, title: '质量控制关联' } },
      { name: 'TM14', path: '/cnas/testing/closeout', component: () => import('#/views/cnas/testing/TM14.vue'), meta: { hideInMenu: true, title: '任务完成与归档' } },
    ],
  },
  {
    name: 'CnasReport',
    path: '/cnas/report',
    redirect: '/cnas/report/tasks',
    meta: { icon: 'lucide:file-text', order: 21, title: '报告管理' },
    children: [
      { name: 'RM01', path: '/cnas/report/tasks', component: () => import('#/views/cnas/report/RM01.vue'), meta: { icon: 'lucide:files', title: '报告任务列表' } },
      { name: 'RM08', path: '/cnas/report/detail', component: () => import('#/views/cnas/report/RM08.vue'), meta: { icon: 'lucide:file-search', title: '报告详情与版本' } },
      { name: 'RM02', path: '/cnas/report/editor', component: () => import('#/views/cnas/report/RM02.vue'), meta: { hideInMenu: true, title: '报告编制' } },
      { name: 'RM03', path: '/cnas/report/preview', component: () => import('#/views/cnas/report/RM03.vue'), meta: { hideInMenu: true, title: '报告预览与完整性检查' } },
      { name: 'RM04', path: '/cnas/report/review', component: () => import('#/views/cnas/report/RM04.vue'), meta: { hideInMenu: true, title: '报告审核' } },
      { name: 'RM05', path: '/cnas/report/approval', component: () => import('#/views/cnas/report/RM05.vue'), meta: { hideInMenu: true, title: '授权签发' } },
      { name: 'RM06', path: '/cnas/report/accreditation-check', component: () => import('#/views/cnas/report/RM06.vue'), meta: { hideInMenu: true, title: '认可标识与声明核验' } },
      { name: 'RM07', path: '/cnas/report/delivery', component: () => import('#/views/cnas/report/RM07.vue'), meta: { hideInMenu: true, title: '报告发布与送达' } },
      { name: 'RM09', path: '/cnas/report/correction', component: () => import('#/views/cnas/report/RM09.vue'), meta: { hideInMenu: true, title: '报告更正' } },
      { name: 'RM10', path: '/cnas/report/withdrawal', component: () => import('#/views/cnas/report/RM10.vue'), meta: { hideInMenu: true, title: '报告撤回与作废' } },
      { name: 'RM11', path: '/cnas/report/archive', component: () => import('#/views/cnas/report/RM11.vue'), meta: { hideInMenu: true, title: '报告归档与调阅' } },
    ],
  },
  {
    name: 'CnasResource',
    path: '/cnas/resource',
    redirect: '/cnas/resource/personnel',
    meta: { icon: 'lucide:boxes', order: 22, title: '资源管理' },
    children: [
      { name: 'R01', path: '/cnas/resource/personnel', component: () => import('#/views/cnas/resource/R01.vue'), meta: { icon: 'lucide:users', title: '人员档案' } },
      { name: 'R03', path: '/cnas/resource/training', component: () => import('#/views/cnas/resource/R03.vue'), meta: { icon: 'lucide:graduation-cap', title: '培训计划' } },
      { name: 'R05', path: '/cnas/resource/competence', component: () => import('#/views/cnas/resource/R05.vue'), meta: { icon: 'lucide:badge-check', title: '人员能力评价' } },
      { name: 'R07', path: '/cnas/resource/methods', component: () => import('#/views/cnas/resource/R07.vue'), meta: { icon: 'lucide:book-open-check', title: '方法标准台账' } },
      { name: 'R11', path: '/cnas/resource/equipment', component: () => import('#/views/cnas/resource/R11.vue'), meta: { icon: 'lucide:settings-2', title: '设备台账' } },
      { name: 'R15', path: '/cnas/resource/materials', component: () => import('#/views/cnas/resource/R15.vue'), meta: { icon: 'lucide:package', title: '物料与批次库存' } },
      { name: 'R18', path: '/cnas/resource/environment', component: () => import('#/views/cnas/resource/R18.vue'), meta: { icon: 'lucide:thermometer', title: '设施环境监控' } },
      { name: 'R20', path: '/cnas/resource/suppliers', component: () => import('#/views/cnas/resource/R20.vue'), meta: { icon: 'lucide:handshake', title: '供应商准入' } },
      { name: 'R22', path: '/cnas/resource/purchase', component: () => import('#/views/cnas/resource/R22.vue'), meta: { icon: 'lucide:shopping-cart', title: '采购申请与审批' } },
      { name: 'R25', path: '/cnas/resource/subcontract', component: () => import('#/views/cnas/resource/R25.vue'), meta: { icon: 'lucide:git-branch', title: '分包评审与客户同意' } },
      { name: 'R02', path: '/cnas/resource/personnel/qualifications', component: () => import('#/views/cnas/resource/R02.vue'), meta: { hideInMenu: true, title: '人员资质与经历' } },
      { name: 'R04', path: '/cnas/resource/training/execution', component: () => import('#/views/cnas/resource/R04.vue'), meta: { hideInMenu: true, title: '培训执行与考核' } },
      { name: 'R06', path: '/cnas/resource/competence/matrix', component: () => import('#/views/cnas/resource/R06.vue'), meta: { hideInMenu: true, title: '能力授权矩阵' } },
      { name: 'R08', path: '/cnas/resource/methods/version', component: () => import('#/views/cnas/resource/R08.vue'), meta: { hideInMenu: true, title: '标准查新与版本' } },
      { name: 'R09', path: '/cnas/resource/methods/validation', component: () => import('#/views/cnas/resource/R09.vue'), meta: { hideInMenu: true, title: '方法验证与确认' } },
      { name: 'R10', path: '/cnas/resource/methods/uncertainty', component: () => import('#/views/cnas/resource/R10.vue'), meta: { hideInMenu: true, title: '测量不确定度与判定规则' } },
      { name: 'R12', path: '/cnas/resource/equipment/calibration', component: () => import('#/views/cnas/resource/R12.vue'), meta: { hideInMenu: true, title: '设备校准与核查计划' } },
      { name: 'R13', path: '/cnas/resource/equipment/maintenance', component: () => import('#/views/cnas/resource/R13.vue'), meta: { hideInMenu: true, title: '设备使用维护记录' } },
      { name: 'R14', path: '/cnas/resource/equipment/exception', component: () => import('#/views/cnas/resource/R14.vue'), meta: { hideInMenu: true, title: '设备异常与影响评价' } },
      { name: 'R16', path: '/cnas/resource/materials/receive', component: () => import('#/views/cnas/resource/R16.vue'), meta: { hideInMenu: true, title: '入库验证与领用' } },
      { name: 'R17', path: '/cnas/resource/materials/alerts', component: () => import('#/views/cnas/resource/R17.vue'), meta: { hideInMenu: true, title: '库存预警与召回' } },
      { name: 'R19', path: '/cnas/resource/environment/exception', component: () => import('#/views/cnas/resource/R19.vue'), meta: { hideInMenu: true, title: '环境异常与影响评价' } },
      { name: 'R21', path: '/cnas/resource/suppliers/performance', component: () => import('#/views/cnas/resource/R21.vue'), meta: { hideInMenu: true, title: '供应商绩效评价' } },
      { name: 'R23', path: '/cnas/resource/purchase/orders', component: () => import('#/views/cnas/resource/R23.vue'), meta: { hideInMenu: true, title: '采购订单与到货跟踪' } },
      { name: 'R24', path: '/cnas/resource/purchase/receive', component: () => import('#/views/cnas/resource/R24.vue'), meta: { hideInMenu: true, title: '采购验收与服务评价' } },
      { name: 'R26', path: '/cnas/resource/subcontract/execution', component: () => import('#/views/cnas/resource/R26.vue'), meta: { hideInMenu: true, title: '分包执行与结果验收' } },
    ],
  },
];

export default routes;
