/* CNAS LIMS candidate prototype: deliberately local-only, with fictional demonstration data. */
const STORAGE_KEY = 'cnas-lims-mvp-v1';
const navGroups = [
  ['工作台', [['dashboard','布局面板','layout-dashboard']]],
  ['业务受理', [['commission','委托受理','clipboard-list'],['samples','检测样品','package-open'],['calibration-assets','校准对象','ruler']]],
  ['执行与复核', [['testing','检测任务','flask-conical'],['calibration','校准任务','gauge'],['review','记录复核','file-check-2']]],
  ['报告与质量', [['reports','报告/证书','file-text'],['resources','资源状态','settings-2'],['capa','质量 CAPA','badge-check']]],
  ['治理与审计', [['permission','权限拒绝','shield-alert'],['audit','审计轨迹','history']]]
];
const viewMeta = {
  dashboard:['工作台','今日待办与预警'], commission:['客户与委托','候选委托受理'], samples:['检测执行','样品接收与流转'], testing:['检测执行','检测任务'], calibrationAssets:['校准执行','被校对象'], calibration:['校准执行','校准任务'], review:['结果管理','记录复核'], reports:['报告交付','报告与证书'], resources:['资源管理','资源状态'], capa:['质量管理','不符合与 CAPA'], permission:['系统治理','权限控制'], audit:['系统治理','本地审计轨迹']
};
const defaultState = () => ({ loggedIn:false, role:'检测员', resourceValid:false, testing:'待执行', calibration:'待执行', review:'待复核', report:'待发布', capa:'待处理', audit:[
  {time:'2026-07-28 10:20', actor:'质量负责人', action:'创建 CAPA', detail:'CAPA-2026-014：资源状态异常的影响评价'},
  {time:'2026-07-28 10:12', actor:'系统模拟', action:'标记资源失效', detail:'EQ-032 恒温恒湿箱校准状态已过期'},
  {time:'2026-07-28 09:45', actor:'检测员', action:'提交原始记录', detail:'TASK-T-0268 记录版本 V1'}
]});
let state = loadState();
let currentView = 'dashboard';
const $ = selector => document.querySelector(selector);
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function loadState(){ try { return {...defaultState(), ...JSON.parse(localStorage.getItem(STORAGE_KEY))}; } catch { return defaultState(); } }
function saveState(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function icon(name){ return `<i data-lucide="${name}"></i>`; }
function refreshIcons(){ if(window.lucide) window.lucide.createIcons(); }
function status(text,type='info'){ return `<span class="status ${type}">${text}</span>`; }
function button(label, action, style='primary', iconName=''){ return `<button class="button ${style}" data-action="${action}">${iconName ? icon(iconName):''}<span>${label}</span></button>`; }
function disabledButton(label, style='secondary', iconName=''){ return `<button class="button ${style}" disabled title="请先完成前置条件">${iconName ? icon(iconName):''}<span>${label}</span></button>`; }
function panel(title, body, extra=''){ return `<section class="panel ${extra}"><h2 class="panel-title">${title}</h2>${body}</section>`; }
function heading(title, subtitle, actions='') { return `<div class="breadcrumb"><span>CNAS LIMS</span><span>/</span><span>${viewMeta[currentView]?.[0] || '候选原型'}</span><span>/</span><span>${title}</span></div><div class="page-heading"><div><h1>${title}</h1><p class="page-subtitle">${subtitle}</p></div><div class="heading-actions">${actions}</div></div>`; }
function audit(action,detail){ state.audit.unshift({time:new Date().toLocaleString('zh-CN',{hour12:false}),actor:state.role,action,detail}); state.audit=state.audit.slice(0,18); saveState(); }
function toast(title,message,type='brand'){ const el=document.createElement('div'); el.className=`toast ${type}`; el.innerHTML=`${icon(type === 'danger' ? 'circle-x' : type === 'warning' ? 'triangle-alert' : 'circle-check')}<div><strong>${title}</strong><span>${message}</span></div>`; $('#toast-region').append(el); refreshIcons(); setTimeout(()=>el.remove(),4200); }
function getPathView(){ const key=location.hash.replace('#/',''); return navGroups.flatMap(group=>group[1]).some(item=>item[0]===key) ? key : 'dashboard'; }
function appShell(){ return `<div class="app-shell"><aside class="sidebar" aria-label="主导航"><div class="brand"><span class="brand-mark">C</span><span>CNAS LIMS</span></div><nav id="navigation" class="navigation"></nav><div class="sidebar-footer">${icon('shield-check')}<span>本地模拟数据</span></div></aside><main class="main-area"><header class="topbar"><button class="icon-button mobile-only" data-action="toggle-menu" aria-label="展开导航" title="展开导航">${icon('menu')}</button><label class="search">${icon('search')}<input id="global-search" type="search" placeholder="搜索样品、任务、报告、文件" /></label><div class="top-actions"><button class="icon-button" data-action="show-notices" aria-label="通知" title="通知">${icon('bell')}<span class="notice-dot"></span></button><div class="current-user"><div><strong>QL</strong><span>${escapeHtml(state.role)}</span></div></div><button class="avatar" data-action="show-profile" aria-label="账户菜单" title="账户菜单">QL</button></div></header><div id="page-content" class="page-content" tabindex="-1"></div></main></div>`; }
function renderLogin(){ const roles=[['检测员','执行检测任务与记录提交','flask-conical'],['校准员','执行校准任务与记录提交','gauge'],['质量负责人','复核记录与处置 CAPA','badge-check'],['授权签字人','发起报告/证书发布','key-round']]; $('#app').innerHTML=`<div class="login-shell"><section class="login-brand"><div class="brand"><span class="brand-mark">C</span><span>CNAS LIMS</span></div><div><h1>实验室流程仿真原型</h1><p>选择一个业务角色，体验检测、校准、质量和报告交付的候选流程。</p><div class="login-points"><div class="login-point">${icon('workflow')}<span>检测与校准双业务线</span></div><div class="login-point">${icon('shield-check')}<span>资源阻断与质量闭环</span></div><div class="login-point">${icon('history')}<span>本地审计与可重置状态</span></div></div></div><div class="login-footer">演示环境 · 仅含虚构数据</div></section><main class="login-main"><section class="login-card"><h2>登录原型</h2><p>请选择本次走查角色。角色切换仅在登录页进行。</p><div class="role-cards">${roles.map(([role,detail,iconName])=>`<button class="role-card ${state.role===role?'active':''}" data-action="select-login-role" data-role="${role}">${icon(iconName)}${state.role===role?`<i class="role-check" data-lucide="circle-check"></i>`:''}<strong>${role}</strong><span>${detail}</span></button>`).join('')}</div><div class="login-actions"><small>无需账号或密码</small>${button('进入原型','login','primary','log-in')}</div></section></main></div>`; refreshIcons(); }
function renderNavigation(){ $('#navigation').innerHTML=navGroups.map(([title,items])=>`<section class="nav-group"><span class="nav-group-title">${title}</span>${items.map(([id,label,ic])=>`<button class="nav-item ${currentView===id?'active':''}" data-view="${id}">${icon(ic)}<span>${label}</span></button>`).join('')}</section>`).join(''); }
function renderDashboard(){ return `${heading('工作台','面向检测与校准业务的本地走查视图', button('重置模拟','confirm-reset','secondary','rotate-ccw'))}<div class="grid metrics"><article class="panel metric"><div class="metric-label">今日待处理任务</div><div class="metric-value">12</div><div class="metric-foot">较昨日 <b>+3</b>，含 4 项待复核</div></article><article class="panel metric warning"><div class="metric-label">资源预警</div><div class="metric-value">3</div><div class="metric-foot">1 项资源状态已影响任务分配</div></article><article class="panel metric danger"><div class="metric-label">待交付报告/证书</div><div class="metric-value">6</div><div class="metric-foot">1 个发布请求待恢复</div></article><article class="panel metric success"><div class="metric-label">CAPA 关闭率</div><div class="metric-value">86%</div><div class="metric-foot">本月 12 项中已关闭 10 项</div></article></div><div class="grid two" style="margin-top:16px"><section class="panel"><h2 class="panel-title">我的待办 <small>按优先级排序</small></h2><div class="table-wrap"><table><thead><tr><th>编号</th><th>事项</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>TASK-T-0268</td><td>水质样品检测记录</td><td>${status(state.testing,'warning')}</td><td><button class="link-action" data-view="testing">进入处理</button></td></tr><tr><td>REV-2026-073</td><td>原始记录技术复核</td><td>${status(state.review,'brand')}</td><td><button class="link-action" data-view="review">开始复核</button></td></tr><tr><td>CAPA-2026-014</td><td>资源失效影响评价</td><td>${status(state.capa,'danger')}</td><td><button class="link-action" data-view="capa">查看事项</button></td></tr></tbody></table></div></section><section class="panel"><h2 class="panel-title">流程状态</h2><div class="steps"><div class="step done"><span class="step-num">1</span>委托受理</div><div class="step done"><span class="step-num">2</span>任务执行</div><div class="step active"><span class="step-num">3</span>记录复核</div><div class="step"><span class="step-num">4</span>报告交付</div></div><div class="alert">${icon('triangle-alert')}<div><strong>资源校验发现异常</strong>恒温恒湿箱 EQ-032 已过有效期，检测任务的继续执行将被阻断。请先完成影响评价或恢复资源状态。</div></div><div class="button-group" style="margin-top:14px">${button('查看资源状态','go-resources','warning','settings-2')}${button('查看本地审计','go-audit','secondary','history')}</div></section></div>`; }
function renderCommission(){ return `${heading('委托受理','候选委托的合同评审与任务分派模拟',button('新建委托','show-commission','primary','plus'))}${panel('筛选条件',`<div class="filters"><label class="field">委托编号<input placeholder="请输入委托编号" /></label><label class="field">业务类型<select><option>全部</option><option>检测</option><option>校准</option></select></label><label class="field">接收日期<input value="2026-07-01 至 2026-07-31" /></label><div class="button-group">${button('查询','filter','primary','search')}${button('重置','filter-reset','secondary')}</div></div>`)}<div style="height:16px"></div>${panel('候选委托列表',commissionTable())}`; }
function commissionTable(){ return `<div class="table-wrap"><table><thead><tr><th>委托编号</th><th>客户</th><th>业务类型</th><th>能力/资源评审</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>COM-2026-0087</td><td>华东环境科技有限公司</td><td>检测</td><td>待确认</td><td>${status('待评审','warning')}</td><td><button class="link-action" data-action="open-detail">查看</button></td></tr><tr><td>COM-2026-0088</td><td>新岳仪器制造有限公司</td><td>校准</td><td>通过</td><td>${status('已接受','success')}</td><td><button class="link-action" data-view="calibration-assets">查看对象</button></td></tr></tbody></table></div><div class="pagination">共 2 条 <button>1</button></div>`; }
function renderSamples(){ return `${heading('检测样品','样品接收、入库和流转记录模拟',button('登记接收','sample-receive','primary','scan-barcode'))}<div class="grid two"><section class="panel"><h2 class="panel-title">样品链路</h2><div class="steps"><div class="step done"><span class="step-num">1</span>接收核对</div><div class="step done"><span class="step-num">2</span>唯一标识</div><div class="step active"><span class="step-num">3</span>在库待领</div><div class="step"><span class="step-num">4</span>检测中</div></div>${panel('样品摘要',`<dl class="key-value"><dt>样品编号</dt><dd>SMP-2026-0147</dd><dt>样品名称</dt><dd>地表水（虚构示例）</dd><dt>当前状态</dt><dd>${status('在库待领','brand')}</dd><dt>存放位置</dt><dd>A 区 / 冷藏柜 C-02</dd></dl>`,'compact')}</section><section class="panel"><h2 class="panel-title">接收异常</h2><div class="empty">${icon('package-check')}<div><p>当前没有待处置的样品接收异常</p><p>异常样品会被隔离，不能直接进入检测任务。</p></div></div></section></div>`; }
function taskTable(type){ const isTest=type==='testing'; const key=isTest?'TASK-T-0268':'TASK-C-0136'; const taskState=isTest?state.testing:state.calibration; return `<div class="table-wrap"><table><thead><tr><th>任务编号</th><th>${isTest?'样品/项目':'被校对象/测量点'}</th><th>执行人</th><th>资源校验</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>${key}</td><td>${isTest?'水质样品 / pH 值':'压力表 / 0.4 MPa'}</td><td>${isTest?'李晓':'陈凌'}</td><td>${state.resourceValid ? status('通过','success') : status('阻断','danger')}</td><td>${status(taskState,taskState==='已完成'?'success':taskState==='已阻断'?'danger':'warning')}</td><td><button class="link-action" data-action="${isTest?'run-testing':'run-calibration'}">${taskState==='已完成'?'查看记录':'推进任务'}</button></td></tr></tbody></table></div>`; }
function renderTesting(){ const blocked=!state.resourceValid; const canSubmit=state.testing==='已完成' && state.resourceValid; return `${heading('检测任务','检测项目、资源校验和原始记录的状态模拟',button('查看记录','open-detail','secondary','file-search'))}${blocked?`<div class="alert">${icon('triangle-alert')}<div><strong>资源校验未通过，任务已阻断</strong>EQ-032 恒温恒湿箱校准状态已过期。恢复资源有效性后可继续任务。</div></div><div style="height:16px"></div>`:''}${panel('检测任务列表',taskTable('testing'))}<div style="height:16px"></div>${panel('处理动作',`<div class="button-group">${button('执行资源校验','run-testing','primary','circle-play')}${button('查看资源','go-resources','secondary','settings-2')}${canSubmit?button('提交记录','submit-record','primary','send'):disabledButton('提交记录','secondary','send')}</div><p class="page-subtitle">提交记录会创建候选版本并进入技术复核；未通过资源校验时无法提交。</p>`)}`; }
function renderCalibrationAssets(){ return `${heading('校准对象','被校对象接收、前检查与状态记录模拟',button('登记对象','asset-receive','primary','plus'))}<div class="grid two"><section class="panel"><h2 class="panel-title">被校对象摘要</h2><dl class="key-value"><dt>对象编号</dt><dd>CAL-A-2026-0061</dd><dt>对象名称</dt><dd>数字压力计（虚构示例）</dd><dt>现场/实验室</dt><dd>实验室校准</dd><dt>前检查</dt><dd>${status('已通过','success')}</dd><dt>交接状态</dt><dd>${status('待校准','brand')}</dd></dl></section><section class="panel"><h2 class="panel-title">流程提醒</h2><div class="alert">${icon('info')}<div><strong>校准前检查已完成</strong>对象识别、外观和环境条件均为模拟记录。现场校准场景需要额外记录地点和离场状态。</div></div></section></div>`; }
function renderCalibration(){ return `${heading('校准任务','测量点、参考设备和不确定度记录的状态模拟',button('查看对象','go-cal-assets','secondary','ruler'))}${panel('校准任务列表',taskTable('calibration'))}<div style="height:16px"></div>${panel('任务推进',`<div class="steps"><div class="step done"><span class="step-num">1</span>资源校验</div><div class="step ${state.calibration==='已完成'?'done':'active'}"><span class="step-num">2</span>测量执行</div><div class="step ${state.calibration==='已完成'?'active':''}"><span class="step-num">3</span>记录提交</div><div class="step"><span class="step-num">4</span>技术审核</div></div><div class="button-group">${button('完成校准记录','run-calibration','primary','circle-play')}${button('提交技术复核','submit-record','secondary','send')}</div>`)}`; }
function renderReview(){ const approved=state.review==='已通过'; return `${heading('记录复核','技术复核、退回与版本留痕模拟',button('查看审计','go-audit','secondary','history'))}<div class="grid two"><section class="panel"><h2 class="panel-title">复核对象</h2><dl class="key-value"><dt>记录编号</dt><dd>REC-T-0268-V1</dd><dt>关联任务</dt><dd>TASK-T-0268</dd><dt>提交人</dt><dd>李晓（检测员）</dd><dt>当前状态</dt><dd>${status(state.review,approved?'success':'warning')}</dd><dt>资源快照</dt><dd>${state.resourceValid?'资源校验通过':'EQ-032 存在失效风险'}</dd></dl></section><section class="panel"><h2 class="panel-title">复核意见</h2><label class="field">意见说明<textarea id="review-note" style="min-height:98px;padding:9px;border:1px solid var(--line);border-radius:4px;resize:vertical" placeholder="填写候选复核意见（仅本地保存）"></textarea></label><div class="button-group" style="margin-top:14px">${button('退回修改','confirm-reject','danger','undo-2')}${button('复核通过','approve-review','primary','check')}</div></section></div><div style="height:16px"></div>${panel('审批时间线',timeline([{t:'提交原始记录',m:'李晓 · 2026-07-28 09:45',d:'记录 REC-T-0268-V1 已提交技术复核。',c:'brand'},{t:approved?'技术复核通过':'待技术复核',m:'质量负责人 · 当前',d:approved?'该记录已锁定为候选复核版本。':'请核验资源、方法和结果记录的完整性。',c:approved?'':'warning'}]))}`; }
function renderReports(){ const isFailed=state.report==='发布失败'; const published=state.report==='已发布'; return `${heading('报告与证书','候选报告审核、批准与发布恢复模拟',button('查看审计','go-audit','secondary','history'))}${isFailed?`<div class="alert">${icon('triangle-alert')}<div><strong>发布请求未确认送达</strong>本地模拟渠道返回超时。系统未生成第二版本，您可对相同文号和版本执行受控重试。</div></div><div style="height:16px"></div>`:''}<div class="grid two"><section class="panel"><h2 class="panel-title">文档状态</h2><dl class="key-value"><dt>文号 / 版本</dt><dd>RPT-2026-0189 / V1</dd><dt>文档类型</dt><dd>检测报告（虚构示例）</dd><dt>审核状态</dt><dd>${status('已审核','success')}</dd><dt>批准状态</dt><dd>${status('已批准','success')}</dd><dt>发布状态</dt><dd>${status(state.report,published?'success':isFailed?'danger':'warning')}</dd></dl></section><section class="panel"><h2 class="panel-title">受控操作</h2><p class="page-subtitle">发布演示保持同一文号、版本和请求标识；不会模拟真实电子签名或外部交付。</p><div class="button-group" style="margin-top:18px">${!published?button(isFailed?'受控重试发布':'模拟发布失败','publish-report','primary','send'):button('查看发布回执','show-receipt','secondary','receipt')} ${button('模拟权限拒绝','go-permission','secondary','shield-alert')}</div></section></div><div style="height:16px"></div>${panel('发布记录',timeline([{t:'文档批准',m:'授权签字人 · 2026-07-28 10:05',d:'候选批准状态已写入本地审计。',c:'brand'},{t:isFailed?'发布失败':published?'发布确认':'等待发布',m:isFailed?'系统模拟 · 2026-07-28 10:08':published?'本地模拟渠道 · 当前':'待触发',d:isFailed?'模拟渠道超时，尚未确认接收方送达。':published?'已记录模拟交付回执。':'可触发一次模拟失败以验证恢复路径。',c:isFailed?'danger':published?'':'info'}]))}`; }
function renderResources(){ const valid=state.resourceValid; return `${heading('资源状态','设备有效性及其对任务分配的候选阻断规则',button(valid?'模拟资源失效':'恢复资源状态','toggle-resource',valid?'danger':'primary',valid?'circle-x':'circle-check'))}<div class="grid two"><section class="panel"><h2 class="panel-title">关键资源</h2><div class="table-wrap"><table><thead><tr><th>资源编号</th><th>资源名称</th><th>有效性</th><th>影响</th></tr></thead><tbody><tr><td>EQ-032</td><td>恒温恒湿箱</td><td>${status(valid?'有效':'已过期',valid?'success':'danger')}</td><td>${valid?'可用于任务分配':'阻断 TASK-T-0268'}</td></tr><tr><td>EQ-018</td><td>标准压力源</td><td>${status('有效','success')}</td><td>可用于校准任务</td></tr></tbody></table></div></section><section class="panel"><h2 class="panel-title">影响评价</h2>${valid?`<div class="empty">${icon('circle-check')}<div><p>当前资源状态可支持候选任务推进</p><p>资源状态变更会产生本地审计记录。</p></div></div>`:`<div class="alert">${icon('triangle-alert')}<div><strong>检测任务已阻断</strong>资源 EQ-032 的模拟有效期已过。恢复资源状态后可继续检测任务，阻断与恢复都会进入审计轨迹。</div></div><div class="button-group" style="margin-top:16px">${button('查看受影响任务','go-testing','secondary','flask-conical')}${button('创建 CAPA','go-capa','primary','badge-check')}</div>`}</section></div>`; }
function renderCapa(){ const closed=state.capa==='已关闭'; const canClose=state.resourceValid && !closed; return `${heading('质量 CAPA','不符合、影响评价、措施验证和关闭模拟',button('查看审计','go-audit','secondary','history'))}<div class="grid two"><section class="panel"><h2 class="panel-title">CAPA-2026-014</h2><dl class="key-value"><dt>来源</dt><dd>资源状态异常</dd><dt>影响范围</dt><dd>TASK-T-0268 及相关候选报告</dd><dt>责任人</dt><dd>质量负责人</dd><dt>当前状态</dt><dd>${status(state.capa,closed?'success':'danger')}</dd><dt>关闭条件</dt><dd>措施完成且由独立角色完成候选验证</dd></dl></section><section class="panel"><h2 class="panel-title">处置操作</h2><div class="steps"><div class="step done"><span class="step-num">1</span>记录发现</div><div class="step done"><span class="step-num">2</span>影响评价</div><div class="step ${closed?'done':'active'}"><span class="step-num">3</span>验证措施</div><div class="step ${closed?'active':''}"><span class="step-num">4</span>关闭</div></div><div class="button-group">${canClose?button('验证并关闭','close-capa','primary','check-circle'):disabledButton(closed?'已关闭':'验证并关闭','secondary','check-circle')}${button('退回处理','reopen-capa','secondary','undo-2')}</div></section></div><div style="height:16px"></div>${panel('处置时间线',timeline([{t:'创建 CAPA',m:'质量负责人 · 2026-07-28 10:20',d:'针对 EQ-032 失效创建候选影响评价。',c:'danger'},{t:closed?'验证并关闭':'等待验证',m:closed?'质量负责人 · 当前':'待处理',d:closed?'已记录本地关闭动作；不代表实际质量记录关闭。':'恢复资源状态后可执行候选验证和关闭。',c:closed?'brand':'warning'}]))}`; }
function renderPermission(){ return `${heading('权限拒绝','权限不足状态及恢复引导的候选演示')}<section class="panel permission">${icon('shield-alert')}<div><h2>权限不足</h2><p>当前角色“${escapeHtml(state.role)}”不具备报告签发权限。请返回登录页选择授权签字人，或返回工作台继续处理当前角色可访问的任务。</p><div class="button-group" style="justify-content:center">${button('返回工作台','go-dashboard','secondary','arrow-left')}${button('返回登录页','confirm-logout','primary','log-out')}</div></div></section>`; }
function renderAudit(){ return `${heading('本地审计轨迹','所有模拟状态变化仅记录在当前浏览器中',button('重置模拟','confirm-reset','secondary','rotate-ccw'))}${panel('操作记录',`<div class="timeline">${state.audit.map(item=>`<article class="timeline-item"><span class="timeline-dot info"></span><div><div class="timeline-title">${escapeHtml(item.action)}</div><div class="timeline-meta">${escapeHtml(item.actor)} · ${escapeHtml(item.time)}</div><div class="timeline-desc">${escapeHtml(item.detail)}</div></div></article>`).join('')}</div>`)} `; }
function timeline(items){ return `<div class="timeline">${items.map(item=>`<article class="timeline-item"><span class="timeline-dot ${item.c||''}"></span><div><div class="timeline-title">${item.t}</div><div class="timeline-meta">${item.m}</div><div class="timeline-desc">${item.d}</div></div></article>`).join('')}</div>`; }
const renderers = {dashboard:renderDashboard,commission:renderCommission,samples:renderSamples,testing:renderTesting,'calibration-assets':renderCalibrationAssets,calibration:renderCalibration,review:renderReview,reports:renderReports,resources:renderResources,capa:renderCapa,permission:renderPermission,audit:renderAudit};
function render(){ if(!state.loggedIn){ renderLogin(); return; } if(!$('#app .app-shell')) $('#app').innerHTML=appShell(); currentView=getPathView(); renderNavigation(); $('#page-content').innerHTML=(renderers[currentView] || renderDashboard)(); $('#page-content').focus({preventScroll:true}); refreshIcons(); }
function go(view){ location.hash=`#/${view}`; }
function closeModal(){ $('#modal-root').innerHTML=''; }
function openModal(title,message,confirmLabel,onConfirm,danger=false){ $('#modal-root').innerHTML=`<div class="overlay"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">${title}</h2><p>${message}</p><div class="modal-actions">${button('取消','close-modal','secondary')}${button(confirmLabel,'modal-confirm',danger?'danger':'primary')}</div></section></div>`; $('#modal-root').dataset.confirm='active'; $('#modal-root')._onConfirm=onConfirm; refreshIcons(); }
function openForm(title, description, fields, onSubmit){ $('#modal-root').innerHTML=`<div class="overlay"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">${title}</h2><p>${description}</p><div class="grid" style="gap:12px">${fields.map(field=>`<label class="field">${field.label}${field.options?`<select data-form-field="${field.key}">${field.options.map(option=>`<option>${option}</option>`).join('')}</select>`:`<input data-form-field="${field.key}" value="${field.value||''}" placeholder="${field.placeholder||''}" />`}</label>`).join('')}</div><div class="modal-actions" style="margin-top:18px">${button('取消','close-modal','secondary')}${button('确认登记','form-submit','primary','check')}</div></section></div>`; $('#modal-root')._onSubmit=onSubmit; refreshIcons(); }
function openDrawer(kind='record'){ let title='候选记录详情'; let body=`<dl class="key-value"><dt>业务编号</dt><dd>TASK-T-0268</dd><dt>当前状态</dt><dd>${status(state.testing,state.testing==='已完成'?'success':'warning')}</dd><dt>责任角色</dt><dd>${escapeHtml(state.role)}</dd><dt>资源快照</dt><dd>${state.resourceValid?'EQ-032 有效':'EQ-032 失效，需进行影响评价'}</dd><dt>返回目标</dt><dd>保留当前业务上下文</dd></dl><div style="height:18px"></div>${panel('候选说明','<p class="page-subtitle">本详情抽屉仅展示虚构示例字段，不连接业务记录或真实文件。</p>','compact')}`; if(kind==='notices'){title='通知中心';body=timeline([{t:'资源预警',m:'刚刚',d:'EQ-032 状态失效，相关检测任务已被阻断。',c:'danger'},{t:'待复核记录',m:'10 分钟前',d:'REC-T-0268-V1 等待质量负责人复核。',c:'warning'},{t:'发布状态',m:'30 分钟前',d:'报告交付流程可进行候选走查。',c:'brand'}]);} if(kind==='profile'){title='账户与会话';body=`<dl class="key-value"><dt>当前用户</dt><dd>QL（演示用户）</dd><dt>业务角色</dt><dd>${escapeHtml(state.role)}</dd><dt>数据范围</dt><dd>本地虚构数据</dd><dt>切换角色</dt><dd>请退出后回到登录页选择。</dd></dl><div class="button-group" style="margin-top:24px">${button('退出登录','confirm-logout','danger','log-out')}</div>`;} $('#drawer-root').innerHTML=`<div class="drawer-backdrop" data-action="close-drawer"></div><aside class="drawer" aria-label="${title}"><div class="drawer-head"><h2>${title}</h2><button class="drawer-close" data-action="close-drawer" aria-label="关闭详情">${icon('x')}</button></div>${body}</aside>`; refreshIcons(); }
function requireRole(roles, message){ if(roles.includes(state.role)) return true; toast('权限不足',message,'danger'); go('permission'); return false; }
function handleAction(action, trigger){ switch(action){
  case 'go-resources':go('resources');break; case 'go-audit':go('audit');break; case 'go-testing':go('testing');break; case 'go-capa':go('capa');break; case 'go-cal-assets':go('calibration-assets');break; case 'go-permission':go('permission');break; case 'go-dashboard':go('dashboard');break;
  case 'toggle-menu':$('.sidebar').classList.toggle('open');break; case 'show-notices':openDrawer('notices');break; case 'show-profile':openDrawer('profile');break; case 'filter':toast('筛选已应用','已使用当前筛选条件检索候选示例数据。');break; case 'filter-reset':toast('筛选已重置','已恢复全部候选示例记录。');break;
  case 'show-commission':openForm('新建候选委托','登记内容只保存在本次浏览器会话的模拟审计中。',[{key:'customer',label:'客户名称',value:'华东环境科技有限公司'},{key:'type',label:'业务类型',options:['检测','校准']},{key:'due',label:'期望交付日期',value:'2026-08-05'}],values=>{audit('登记候选委托',`${values.customer} · ${values.type} · 期望交付 ${values.due}`);toast('委托已登记','已创建本地候选委托，等待合同评审。');render();});break;
  case 'sample-receive':openForm('登记样品接收','请填写候选接收信息；异常样品不进入后续任务。',[{key:'sample',label:'样品名称',value:'地表水（虚构示例）'},{key:'quantity',label:'数量',value:'2 瓶'},{key:'location',label:'存放位置',value:'A 区 / 冷藏柜 C-02'}],values=>{audit('登记样品接收',`${values.sample} · ${values.quantity} · ${values.location}`);toast('登记完成','已添加本地模拟接收记录。');render();});break;
  case 'asset-receive':openForm('登记被校对象','请填写候选对象信息；前检查通过后才可进入校准任务。',[{key:'asset',label:'对象名称',value:'数字压力计（虚构示例）'},{key:'serial',label:'序列号',value:'DP-2026-061'},{key:'place',label:'校准地点',options:['实验室校准','现场校准']}],values=>{audit('登记被校对象',`${values.asset} · ${values.serial} · ${values.place}`);toast('登记完成','已添加本地模拟校准对象。');render();});break;
  case 'toggle-resource': state.resourceValid=!state.resourceValid; audit(state.resourceValid?'恢复资源状态':'标记资源失效',state.resourceValid?'EQ-032 已恢复为有效状态。':'EQ-032 已设为失效，相关任务将被阻断。'); saveState(); toast(state.resourceValid?'资源已恢复':'资源已设为失效',state.resourceValid?'候选任务可以重新执行资源校验。':'TASK-T-0268 已进入候选阻断状态。',state.resourceValid?'brand':'warning'); render();break;
  case 'run-testing': if(!state.resourceValid){state.testing='已阻断';audit('阻断检测任务','TASK-T-0268 因 EQ-032 失效未通过资源校验。');saveState();toast('任务已阻断','请先恢复资源状态，再重新执行校验。','danger');render();break;} if(!requireRole(['检测员','质量负责人'],'当前角色无法执行检测任务。')) break; state.testing='已完成';audit('完成检测记录','TASK-T-0268 已完成候选执行，等待提交复核。');saveState();toast('检测记录已完成','可提交候选原始记录进行复核。');render();break;
  case 'run-calibration': if(!state.resourceValid){toast('资源校验未通过','请先恢复资源状态后再推进校准任务。','danger');break;} if(!requireRole(['校准员','质量负责人'],'当前角色无法执行校准任务。')) break; state.calibration='已完成';audit('完成校准记录','TASK-C-0136 已完成候选测量与记录。');saveState();toast('校准记录已完成','可提交技术复核。');render();break;
  case 'submit-record': if(!state.resourceValid){toast('无法提交记录','资源校验未通过时，候选记录不能提交。','danger');break;} state.review='待复核';audit('提交记录复核','已提交候选原始记录至技术复核。');saveState();toast('已提交复核','复核人可进行通过或退回。');go('review');break;
  case 'approve-review': if(!requireRole(['质量负责人'],'只有质量负责人可完成候选技术复核。')) break; state.review='已通过';audit('复核通过','REC-T-0268-V1 已作为候选复核版本锁定。');saveState();toast('复核通过','该动作已写入本地审计轨迹。');render();break;
  case 'confirm-reject': openModal('退回复核记录','退回会保留当前候选版本，并创建一个需要修改的本地待办。','确认退回',()=>{state.review='已退回';audit('退回复核记录','REC-T-0268-V1 被退回，等待提交新版本。');saveState();toast('已退回修改','已生成本地模拟待办。','warning');render();});break;
  case 'publish-report': if(!requireRole(['授权签字人'],'只有授权签字人可以发起候选发布。')) break; if(state.report==='发布失败'){state.report='已发布';audit('受控重试发布','RPT-2026-0189/V1 已在本地模拟渠道确认送达。');toast('发布已确认','已保持原文号和版本，并记录模拟回执。');} else {state.report='发布失败';audit('发布失败','RPT-2026-0189/V1 本地模拟渠道超时。');toast('发布失败','未确认送达，可对同一文号受控重试。','danger');} saveState();render();break;
  case 'show-receipt':openModal('模拟发布回执','文号 RPT-2026-0189 / V1 已在本地模拟渠道确认送达。回执仅用于交互走查。','关闭',()=>{});break;
  case 'close-capa': if(!requireRole(['质量负责人'],'只有质量负责人可关闭候选 CAPA。')) break; if(!state.resourceValid){toast('无法关闭 CAPA','请先恢复资源状态，再完成候选验证。','danger');break;} state.capa='已关闭';audit('关闭 CAPA','CAPA-2026-014 已完成候选验证与本地关闭。');saveState();toast('CAPA 已关闭','关闭动作已写入本地审计。');render();break;
  case 'reopen-capa':state.capa='待处理';audit('退回 CAPA','CAPA-2026-014 已退回候选处置。');saveState();toast('已退回处理','CAPA 回到待处理状态。','warning');render();break;
  case 'select-login-role':state.role=trigger.dataset.role;saveState();render();break;
  case 'login':state.loggedIn=true;saveState();go('dashboard');render();toast('登录成功',`已以 ${state.role} 进入本地仿真原型。`);break;
  case 'confirm-logout':openModal('退出登录','退出后将返回登录页。已产生的本地模拟数据会保留，您可在登录后继续走查。','确认退出',()=>{state.loggedIn=false;saveState();$('#drawer-root').innerHTML='';render();});break;
  case 'confirm-reset': openModal('重置模拟状态','这会清空当前浏览器中的候选操作记录，并恢复初始虚构数据。','确认重置',()=>{const role=state.role;state={...defaultState(),loggedIn:true,role};saveState();toast('模拟状态已重置','已恢复初始虚构数据与审计记录。');go('dashboard');});break;
  case 'open-detail':openDrawer();break; case 'close-drawer':$('#drawer-root').innerHTML='';break; case 'close-modal':closeModal();break; case 'modal-confirm':{const fn=$('#modal-root')._onConfirm;closeModal();if(fn)fn();}break; case 'form-submit':{const values={}; document.querySelectorAll('[data-form-field]').forEach(field=>values[field.dataset.formField]=field.value.trim());const fn=$('#modal-root')._onSubmit;closeModal();if(fn)fn(values);}break;
  default: toast('候选交互','该入口在 MVP 中展示为本地模拟操作。');
} }
document.addEventListener('click',event=>{ const nav=event.target.closest('[data-view]'); if(nav){go(nav.dataset.view);return;} const action=event.target.closest('[data-action]'); if(action) handleAction(action.dataset.action,action); });
document.addEventListener('keydown',event=>{if(event.target.id==='global-search' && event.key==='Enter')toast('搜索演示',`已在候选数据中检索“${event.target.value || '全部'}”。`);});
window.addEventListener('hashchange',render); if(!location.hash) location.hash='#/dashboard'; render();
